apiVersion: v1
kind: Service
metadata:
  name: smartinventory-service
  labels:
    app: smartinventory
    tier: backend
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-path: "/auth/"
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-port: "traffic-port"
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-protocol: "HTTP"
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: smartinventory
    tier: backend
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  labels:
    app: smartinventory
    tier: database
spec:
  type: ClusterIP
  ports:
  - port: 3306
    targetPort: 3306
    protocol: TCP
    name: mysql
  selector:
    app: smartinventory
    tier: database
