apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "smartinventory.fullname" . }}-config
  labels:
    {{- include "smartinventory.labels" . | nindent 4 }}
data:
  {{- toYaml .Values.configMap.data | nindent 2 }}
