apiVersion: v1
kind: Secret
metadata:
  name: {{ include "smartinventory.fullname" . }}-secret
  labels:
    {{- include "smartinventory.labels" . | nindent 4 }}
type: Opaque
data:
  db-password: {{ .Values.secret.data.db.password | quote }}
